# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: Seongjun (Ryan) Kang
description: |
  <span class="lead-line">Ph.D. candidate in human-computer interaction</span>
  <span class="lead-line"><a href="https://sites.google.com/view/gist-hcis-lab/home" target="_blank" rel="noopener noreferrer">HCIS Lab</a>, Gwangju Institute of Science and Technology (GIST)</span>
url: https://ksjryan.github.io
baseurl: ''

author:
  name: Seongjun Kang
  url: https://ksjryan.github.io

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true

nav:
  - title: "Home"
    url: /#home
  - title: "Publications"
    url: /#research
  - title: "Fun Projects"
    url: /#fun-project
