# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: Seongjun Kang
description: |
  <p style="font-size: 16px;">Ph.D. student in<br>human-computer interaction</p>
  <p style="font-size: 16px;">working at the <a href="https://sites.google.com/view/gist-hcis-lab/home">HCIS Lab.</a> in the Gwangju Institute of Science and Technology (GIST)</p>
url: https://ksjryan.github.io
baseurl: ''

author:
  name: Andrew Fong
  url: https://twitter.com/fongandrewc

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true

nav:
  - title: "About"
    url: /#about
  - title: "Research"
    url: /#research
  - title: "Fun Project"
    url: /#fun-project
